server:
  port: 8002
  profiles:
      active: ${env}
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      #  - id: payment_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
      #    uri: lb://cloud-payment-service #匹配后提供服务的路由地址
      #    predicates:
      #      - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: spring-cloud-admin
          uri: lb://spring-cloud-admin
          predicates:
             - Path=/adminGtw/**
          filters:
             - StripPrefix=1

eureka:
  client:
    registry-fetch-interval-seconds: 5
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
      prefer-ip-address: true
    service-url:
          #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://192.168.1.114:8001/eureka